package ai

import "github.com/zaynkorai/mailflow/util/gmail"

type GraphState struct {
	EmailsInfo         []gmail.EmailInfo // List of emails to process
	CurrentEmailInfo   gmail.EmailInfo   // The email info currently being processed
	EmailCategory      string            // Category assigned to the current email
	GeneratedEmail     string            // The draft email generated by the writer agent
	RAGQueries         []string          // Queries generated for RAG retrieval
	RetrievedDocuments string            // Concatenated documents retrieved from RAG
	WriterMessages     []string          // History of writer's drafts and proofreader feedback
	Sendable           bool              // Indicates if the generated email is sendable
	Trials             int               // Number of attempts to generate a sendable email
}

func NewGraphState() *GraphState {
	return &GraphState{
		EmailsInfo:         []gmail.EmailInfo{},
		WriterMessages:     []string{},
		RAGQueries:         []string{},
		RetrievedDocuments: "",
		Sendable:           false,
		Trials:             0,
	}
}
